CREATE TABLE dbo.dim_date (
    ID_DATE INT PRIMARY KEY,
    DATE_VALUE DATE,
    YEAR INT,
    MONTH INT,
    DAY INT,
    QUARTER INT,
    WEEKOFYEAR INT,
    WEEKDAYNUMBER INT,
    WEEKDAYNAME NVARCHAR(20),
    MONTHNAME NVARCHAR(20),
    DAYTYPE NVARCHAR(10),
    SEASON NVARCHAR(10)
);
